<?php

namespace Brackets\AdminGenerator\Tests\Feature\Users;

use Brackets\AdminGenerator\Tests\UserTestCase;
use File;
use Illuminate\Foundation\Testing\DatabaseMigrations;

class DefaultUserCrudGeneratorTest extends UserTestCase
{
    use DatabaseMigrations;

    /** @test */
    function user_controller_should_be_generated_under_default_namespace(){
        $filePath = base_path('App/Http/Controllers/Admin/UsersController.php');

        $this->assertFileNotExists($filePath);

        $this->artisan('admin:generate:user', [
        ]);

        $this->assertFileExists($filePath);
        $this->assertStringStartsWith('<?php namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use \Illuminate\Http\Response;
use App\Http\Requests\Admin\User\StoreUser;
use App\Http\Requests\Admin\User\UpdateUser;
use Brackets\Admin\AdminListing;
use App\Models\User;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Hash;
use Brackets\AdminAuth\Services\ActivationService;
use Brackets\AdminAuth\Facades\Activation;
use Spatie\Permission\Models\Role;

class UsersController extends Controller', File::get($filePath));
    }

    /** @test */
    function user_store_request_should_be_generate_with_default_name(){
        $filePath = base_path('App/Http/Requests/Admin/User/StoreUser.php');

        $this->assertFileNotExists($filePath);

        $this->artisan('admin:generate:user', [
        ]);

        $this->assertFileExists($filePath);
        $this->assertStringStartsWith('<?php namespace App\Http\Requests\Admin\User;

use Illuminate\Foundation\Http\FormRequest;
use Gate;

class StoreUser extends FormRequest
{', File::get($filePath));
    }

    /** @test */
    function user_update_request_should_be_generate_with_default_name(){
        $filePath = base_path('App/Http/Requests/Admin/User/UpdateUser.php');

        $this->assertFileNotExists($filePath);

        $this->artisan('admin:generate:user', [
        ]);

        $this->assertFileExists($filePath);
        $this->assertStringStartsWith('<?php namespace App\Http\Requests\Admin\User;

use Illuminate\Foundation\Http\FormRequest;
use Gate;
use App\Models\User;

class UpdateUser extends FormRequest
{', File::get($filePath));
    }

    /** @test */
    function user_autogenerated_routes_append(){
        $filePath = base_path('routes/web.php');

        $this->artisan('admin:generate:user', [
        ]);

        $this->assertStringStartsWith('<?php



/* Auto-generated admin routes */
Route::get(\'/admin/user\',                                   \'Admin\UsersController@index\');
Route::get(\'/admin/user/create\',                            \'Admin\UsersController@create\');
Route::post(\'/admin/user/store\',                            \'Admin\UsersController@store\');
Route::get(\'/admin/user/edit/{user}\',                       \'Admin\UsersController@edit\')->name(\'admin/user/edit\');
Route::post(\'/admin/user/update/{user}\',                    \'Admin\UsersController@update\')->name(\'admin/user/update\');
Route::delete(\'/admin/user/destroy/{user}\',                 \'Admin\UsersController@destroy\')->name(\'admin/user/destroy\');
Route::get(\'/admin/user/resend-activation/{user}\',          \'Admin\UsersController@resendActivationEmail\')->name(\'admin/user/resendActivationEmail\');', File::get($filePath));
    }

}
